### ISSUE TITLE
Zandronum reports stack size exceeded when Roam() is used

### ISSUE THREAD

**Issue by ghost** [TarCV/botc#10]
This bug applies to tarcv-master only, don't know if it applies to upgrade.

**Comment by TarCV** [comment]
I think it's because `botc` doesn't drop unused return values from the stack. I'll try to fix it on weekend.

**Comment by TarCV** [comment]
@so-sleepy, seeing your like on that PR, I suppose it fixed the issue for you?

**Comment by ghost** [comment]
You guessed that right, I needed this fix to modify an [annoying behavior of the bots](https://zandronum.com/tracker/view.php?id=3775), which was a bug, thank you so much. Would you mind if I began testing the upgrade branch and submitting issues?

**Comment by TarCV** [comment]
Btw, you might be also interested in [DH_ARRAYSET bug](https://zandronum.com/tracker/view.php?id=3588). From my understanding of bot sources Carnevil's intent doesn't match DH_ARRAYSET implementation.

Help with testing that branch would be really nice, so no issues with that.
Have you encountered any other issues with PR #7?

**Comment by ghost** [comment]
#14 doesn't fix the upgrade branch, I have also commented in #7.
