### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by AirmanRNC** [TarCV/botc#25]

**Comment by TarCV** [comment]
Hi. Sorry for the late reply.
Basically you just download the latest release and run command like `botc script.botc BOTLUMP`, where **script.botc** is a script source file and **BOTLUMP** is a name of output file to be created. Also ` botc_defs.bts` containing various definitions should be in the working directory.
Example botc sources are https://wiki.zandronum.com/CRASHBOT and https://wiki.zandronum.com/HUMANBOT , they might use a bit obsolete syntax, but it should not be hard to fix.
In the worst case you can download [debotc](https://github.com/TarCV/debotc) and decompile bot binaries (like CRASHBOT lump) from zandronum.pk3, after that you'll need to replace integers with booleans where appropriate (or just use `botc_defs.bts` from debotc repository, which doesn't use booleans in definitions at all).
This link might be useful too - https://zandronum.com/forum/viewtopic.php?f=11&t=9941&p=115780

Overall in Zandronum each bot logic consists of two files: it's compiled logic script like CRASHBOT and actual bot definition in BOTINFO lump. That bot definition links to the script with `script` line, see https://wiki.zandronum.com/BOTINFO
