### ISSUE TITLE
Fix build on Linux

### ISSUE THREAD

**Issue by ghost** [TarCV/botc#9]
https://github.com/TarCV/botc/blob/99dbd44f9aa5d9d0469d9b190450a91fe5576a04/namedenums/namedenums.cpp#L181
should be
`void SkipWhitespace (char*& cp, const char *end)`
https://github.com/TarCV/botc/blob/99dbd44f9aa5d9d0469d9b190450a91fe5576a04/namedenums/CMakeLists.txt#L4
should be
`    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /std:c++17 /permissive-")`
https://github.com/TarCV/botc/blob/99dbd44f9aa5d9d0469d9b190450a91fe5576a04/namedenums/CMakeLists.txt#L7
should be
`        set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17 -W -Wall")`

**Comment by ghost** [comment]
#11

**Comment by TarCV** [comment]
Should be fixed with the latest PRs
